#.SYNOPSIS Ansible playbook. Autor: Ariel De Salvo Propato.
#.DESCRIPTION Script created with the goal of deploying a home server, with different services running in containers.
#.NOTES Many of the configurations are dynamic, first check the setupvariables.yml file inside the config folder.
#.COMPONENT Ansible. 

---
   # Play1 - Docker preparation tasks.
  - name: Play Dir/Config - Create Docker directories and configuration files.
    hosts: localhost
    vars_files:
      - config/setupvariables.yml
    become: yes
    become_user: root
    tasks:
    #Some of the directories will be created automatically with the docker-compose,
    #these directories are created only because it had config files.
      - name: Create a directory for docker volumes.
        file:
          path: /{{ volumespath }}/docker/{{ item }}
          owner: root
          group: root
          state: directory
          mode: 0755
        with_items:
        - pihole
        - pihole/etc-pihole
        - nginx
        - nginx/certs
        - dashy
        - samba
      
      - name: Create a directory for share with Samba (Docker).
        file:
          path: /{{ volumespath }}/docker/samba/public
          owner: root
          group: root
          state: directory
          mode: 777

      - name: Creating file for local DNS in Pi-Hole.
        template:
          src: templates/pihole-custom.list
          dest: /{{ volumespath }}/docker/pihole/etc-pihole/custom.list

      - name: Creating file for Nginx configuration.
        template:
          src: templates/nginx-default.conf.template
          dest: /{{ volumespath }}/docker/nginx/nginx-default.conf.template

      - name: Creating file for Dashy configuration.
        template:
          src: templates/dashy-config.yml
          dest: /{{ volumespath }}/docker/dashy/config.yml
      
      - name: Copying icons for Dashy.
        ansible.builtin.command: cp -R templates/item-icons /{{ volumespath }}/docker/dashy/item-icons

      - name: Creating the Docker-Compose file.
        template:
          src: templates/docker-compose.yml
          dest: /{{ volumespath }}/docker-compose.yml
  
  # Play2 - Server preparation tasks.
  - name: Play Update/Install - Update the system and Install of the required packages.
    hosts: localhost
    vars_files:
      - config/setupvariables.yml
    become: yes
    become_user: root
    tasks:
      - name: Update all packages to the latest version.
        apt:
         upgrade: dist

      - name: Install of mkcert.
        apt:
          name: mkcert
          state: present
      
      - name: Install of Docker.
        apt:
          name: docker.io
          state: present
        when: ansible_facts['distribution']=="Ubuntu"
  
      - name: Install of Docker-Compose.
        apt:
          name: docker-compose
          state: present
  
  # Play3 - Certificates related tasks.
  - name: Play MkCert - rootCA installation and creation of certificates for services.
    hosts: localhost
    vars_files:
      - config/setupvariables.yml
    become: yes
    become_user: root
    tasks:
      - name: Install the rootCA.
        ansible.builtin.command: mkcert -install

      - name: Creating the certificates.
        ansible.builtin.command: mkcert -key-file key.pem -cert-file cert.pem duplicati.{{ domain }} dashy.{{ domain }} jellyfin.{{ domain }} kasm.{{ domain }} mysql.{{ domain }} nextcloud.{{ domain }} omv.{{ domain }} portainer.{{ domain }} pihole.{{ domain }} uptimekuma.{{ domain }} transmission.{{ domain }}
      
      - name: Moving the certificates to nginx cert folder.
        ansible.builtin.command: mv key.pem cert.pem /{{ volumespath }}/docker/nginx/certs/
      
      - name: Get CAroot dir.
        shell: mkcert -CAROOT
        register: CAroot

      - name: Coping the rootCA certificate to the share folder.
        ansible.builtin.command: cp /root/.local/share/mkcert/rootCA.pem /{{ volumespath }}/docker/samba/public/rootCA.pem

  # Play4 - Docker-Compose related tasks.
  - name: Play Docker-Compose - Deploy of docker using Docker-Compose yml file.
    hosts: localhost
    vars_files:
      - config/setupvariables.yml
    become: yes
    become_user: root
    tasks:
      - name: Running Docker-Compose.
        shell: chdir=/{{ volumespath }} docker-compose up -d
        register: output

      - debug:
          msg: "{{ output.stderr_lines }}"