#.SYNOPSIS Config file for Ansible playbook. Autor: Ariel De Salvo Propato.
#.DESCRIPTION Configuration file for the Ansible playbook variables and other config files (nginx, pi-hole, dashy, docker-compose).

---
#Initial config vars for Ansible playbook.
domain: hostname #Enter the hostname of your server here.
hostip: X.X.X.X #Enter here the Ip of your Host here.
volumespath: home #Specify here the path where the Docker volumes will be hosted.
default_tz: America/Argentina #Your Time Zone.

#Config vars for Docker Compose yml script.

#MySQL vars
mysql_root_password : changeMe! #Password to access to the MySQL server as root.
#These parameters are required for NextCloud installation, it is recommended to change them.
mysql_database: nextclouddb
mysql_username: nextcloud
mysql_password: nextcloud

#No-ip
noip_username: 
noip_password:
noip_domains:
noip_interval:

#Wireguard
wireguard_tz: America/Argentina # Incase you like use other Time Zone.
wireguard_serverport: 51820 #Optional.
wireguard_peers: 2 #Optional.
wireguard_peerdns: auto #Optional.
wireguard_allowedips: 0.0.0.0/0 #Peer addresses allowed.
wireguard_internal_subnet: 10.13.13.0/24 #Subnet used in VPN tunnel.
wireguard_serverurl: #Wireguard VPN server address (Public IP or Dynamic DNS).

#Pi-Hole
pihole_password: changeMe! #Set a secure password here or it will be random.

#Samba
samba_username: changeMe!
samba_password: changeMe!

#Kibana
kibana_username: changeMe!
kibana_password: changeMe!

#Rsync
rsync_username: changeMe!
rsync_group: changeMe!
rsync_password: changeMe!

#Curator 
#Only change the time of retention.
curator_filter: '[{"filtertype": "pattern", "kind": "prefix", "value": "filebeat-"}, {"filtertype": "age", "source": "name", "direction": "older", "timestring": "%Y.%m.%d", "unit": "days","unit_count": 30}]'

#Select the service you like, recommended services to keep active:
#[dashy, portainer, ngnix, pihole, watchtower, samba]
#Options available: active | disabled
dashy_status: active
portainer_status: active
ngnix_status: active
pihole_status: active
efk_status: active
uptimekuma_status: active
watchtower_status: active
nextcloud_status: active
jellyfin_status: active
transmission_status: active
sonarr_status: active
jackett_status: active
duplicati_status: active
kasm_status: disabled
wireguard_status: disabled
samba_status: active
filebrowser_status: active
noip_status: disabled