 pageInfo:
  title: {{ domain }}
 sections:
  - name: Admin Services
    icon: ''
    items:
      - title: Cockpit
        description: Cockpit
        icon: cockpit.png
        url: https://cockpit.{{ domain }}
        target: newtab
        id: 0_1357_cockpit
      - title: Portainer
        description: Container web manager
        icon: portainer.png
        url: https://portainer.{{ domain }}
        target: newtab
        id: 1_1357_portainer
      - title: Pi-Hole
        description: DNS server and Ad-blocker
        icon: pihole.png
        url: https://pihole.{{ domain }}/admin
        target: newtab
        id: 2_1357_pihole
      - title: Uptime-Kuma
        description: Monitors uptime
        icon: uptimekuma.svg
        url: https://uptimekuma.{{ domain }}
        target: newtab
        id: 3_1357_uptimekuma
      - title: Kibana
        description: Logs
        icon: kibana.png
        url: https://kibana.{{ domain }}
        target: newtab
        id: 4_1357_kibana
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Multimedia Services
    items:
      - title: Jellyfin
        description: >-
          Media System that puts you in control of managing and streaming your
          media.
        icon: jellyfin.png
        url: https://jellyfin.{{ domain }}
        target: newtab
        id: 0_1903_jellyfin
      - title: Transmission
        description: BitTorrent client
        icon: transmission.png
        url: https://transmission.{{ domain }}
        target: newtab
        id: 1_1903_transmission
      - title: Sonarr
        description: >-
          Monitor multiple RSS feeds for new episodes of your favorite shows and
          will grab, sort and rename them
        icon: sonarr.png
        url: https://sonarr.{{ domain }}
        target: newtab
        id: 4_1903_sonarr
      - title: Jackett
        description: Jackett works as a proxy server, it translates queries from apps
        icon: jackett.png
        url: https://jackett.{{ domain }}
        target: newtab
        id: 5_1903_jackett  
      - title: NextCloud
        description: Sync and share files
        icon: nextcloud.png
        url: https://{{ hostip }}:2443 #Using the domain, it's not possible authenticate.
        target: newtab
        id: 2_1903_nextcloud
      - title: FileBrowser
        description: Easily upload/download/copy files and folders
        icon: filebrowser.png
        url: https://filebrowser.{{ domain }}
        target: newtab
        id: 3_1903_filebrowser
  - name: Miscellaneous Services
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Duplicati
        description: Block based backup solution
        icon: duplicati.png
        url: https://duplicati.{{ domain }}
        target: newtab
        id: 0_2232_duplicati
      - title: Resilio
        description: Fast, reliable, and simple file sync and share solution, powered by P2P technology
        icon: resiliosync.png
        url: https://resiliosync.{{ domain }}
        target: newtab
        id: 1_2232_resiliosync
      - title: Syncthing
        description: peer-to-peer file synchronization application
        icon: syncthing.png
        url: https://syncthing.{{ domain }}
        target: newtab
        id: 2_2232_syncthing
      - title: Kasm
        description: Workspaces delivers zero-trust remote browser isolation (RBI)
        icon: kasm.png
        url: https://kasm.{{ domain }}
        target: newtab
        id: 3_2232_kasm
 appConfig:
  theme: dashy-docs
  language: en
  layout: auto
  iconSize: medium
