#Create an account in https://showrss.info/

web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 1440

tasks:
#Use this config as example, if you like to add other Tv Show,
#copy and pase this section and put the new rss link (Feed for this show).
  download-MrRobot:
    rss: https://showrss.info/show/273.rss
    all_series: yes
    transmission:
      host: {{ hostip }}
      port: 9091
      username: {{ transmission_username }}
      password: {{ transmission_password }}

  sort-files:
    find:
      # directory with the files to be sorted
      path: /{{ volumespath }}/docker/transmission/downloads
      # fetch all avi, mkv and mp4 files, skips the .part files (unfinished torrents)
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    seen: local
    # this is needed for the episode names
    thetvdb_lookup: yes
    all_series:
      # for some reason all_series rejects all episodes here, even with seen: local, so parse_only must be added
      parse_only: yes
    # TVDB doesn't recognise "Adventure Time with Finn and Jake" so you must add such exceptions here manually
    series:
      - Adventure Time
    move:
      # this is where the series will be put
      to: /{{ volumespath }}/docker/jellyfin/tvshows/