#Author: https://github.com/pablokbs/plex-rpi/tree/master/flexget

web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 30

templates:
  tv:
    series:
      settings:
        tv:
          exact: yes
          propers: 12 hours
          quality: 720p
      tv:
      - Moonshine

    transmission:
      host: http://{{ hostip }}
      port: 9091
      username: {{ transmission_username }}
      password: {{ transmission_password }}

tasks:
  eztvrss:
    rss: https://eztv.ag/ezrss.xml
    template: tv
    priority: 2